### ISSUE TITLE
Compiling error with Teensy 3.6 

### ISSUE THREAD

**Issue by SteveObert** [MrHaroldA/MS3#1]
Hello,
I have this library working well with an Arduino Uno, however, I get an error when compiling the sample sketch on a Teensy (which is what I want to use for my finished project).

Is there a way to fix this?
Thank you.

Here is the error:

Arduino: 1.8.8 (Mac OS X), TD: 1.45, Board: "Teensy 3.6, All of the Above, 16 MHz (No USB), Debug, US English"

In file included from /Users/steve/Documents/Arduino/deleteMe/deleteMe.ino:12:0:
/Users/steve/Documents/Arduino/libraries/MS3-master/MS3.h: In member function 'bool MS3::receive(long unsigned int&, byte&)':
/Users/steve/Documents/Arduino/libraries/MS3-master/MS3.h:184:46: error: no matching function for call to 'MS3::RecvData(unsigned int*, byte [64])'
             if (MS3::RecvData(&rcvd, incoming) == 0) {
                                              ^
In file included from /Users/steve/Documents/Arduino/libraries/MS3-master/MS3.h:75:0,
                 from /Users/steve/Documents/Arduino/deleteMe/deleteMe.ino:12:
/Users/steve/Documents/Arduino/libraries/USB_Host_Shield_2.0-master/usbh_midi.h:75:17: note: candidate: uint8_t USBH_MIDI::RecvData(uint16_t*, uint8_t*)
         uint8_t RecvData(uint16_t *bytes_rcvd, uint8_t *dataptr);
                 ^
/Users/steve/Documents/Arduino/libraries/USB_Host_Shield_2.0-master/usbh_midi.h:75:17: note:   no known conversion for argument 1 from 'unsigned int*' to 'uint16_t* {aka short unsigned int*}'
/Users/steve/Documents/Arduino/libraries/USB_Host_Shield_2.0-master/usbh_midi.h:76:17: note: candidate: uint8_t USBH_MIDI::RecvData(uint8_t*, bool)
         uint8_t RecvData(uint8_t *outBuf, bool isRaw=false);
                 ^
/Users/steve/Documents/Arduino/libraries/USB_Host_Shield_2.0-master/usbh_midi.h:76:17: note:   no known conversion for argument 1 from 'unsigned int*' to 'uint8_t* {aka unsigned char*}'
Error compiling for board Teensy 3.6.

**Comment by SteveObert** [comment]
Never mind, I got the code to compile by changing the MS3.h file 

I changed **unsigned int rcvd;** to read **uint16_t rcvd;**

**Comment by MrHaroldA** [comment]
Tnx Steve, keep me posted on your project! ;)
