### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by fredimachado** [MrHaroldA/MS3#2]
Hey Harold!

First of all, thanks a lot for all the information you have provided.

I've done some research and I was playing around sending/receiving MIDI messages to/from my Boss GT-1 using a C# application I've built and everything seems to be working fine.

I'm planning on building a simple arduino midi controller with an USB host shield inside a standard guitar pedal enclosure and some foot switches. I've ordered an Arduino Pro Mini 3.3V and a mini USB host shield.

Do you think that's enough to make it work (Any comments)?

Last thing: I assume the GT-1 will send 5V data. If that's right, I also assume that the chip in the host shield will also be fine with it even though it's powered with 3.3V. Should I be worried about this?

Thanks a lot!

**Comment by fredimachado** [comment]
Hi Harold,

I've got the parts, tested it and it works fine.

Thanks!

**Comment by MrHaroldA** [comment]
Glad it works fine! I'm selling my MS-3 as I don't really use it ... so this level of service you got from me will be the ongoing standard ;)
