### ISSUE TITLE
Multiple Includes-> Error

### ISSUE THREAD

**Issue by bauerbyter** [MrHaroldA/MS3#3]
First of all thank you for your work.
I have only one problem, when I include your library in two different header files, it throws some errors.
I looked through it and the Headerguards and all #endif are okay. Do you have an idea whats going on?

Errors: 
`
.pio\build\megaatmega2560\src\main.cpp.o (symbol from plugin): In function `Queue':
(.text+0x0): multiple definition of `Queue'
.pio\build\megaatmega2560\src\control.cpp.o (symbol from plugin):(.text+0x0): first defined here
.pio\build\megaatmega2560\src\main.cpp.o (symbol from plugin): In function `Queue':
(.text+0x0): multiple definition of `dataOut2'
.pio\build\megaatmega2560\src\control.cpp.o (symbol from plugin):(.text+0x0): first defined here
.pio\build\megaatmega2560\src\main.cpp.o (symbol from plugin): In function `Queue':
(.text+0x0): multiple definition of `bstr_G_type'
.pio\build\megaatmega2560\src\control.cpp.o (symbol from plugin):(.text+0x0): first defined here
.pio\build\megaatmega2560\src\main.cpp.o (symbol from plugin): In function `Queue':
(.text+0x0): multiple definition of `bstr_R_type'
.pio\build\megaatmega2560\src\control.cpp.o (symbol from plugin):(.text+0x0): first defined here
.pio\build\megaatmega2560\src\main.cpp.o (symbol from plugin): In function `Queue':
(.text+0x0): multiple definition of `bstr_Y_type'
.pio\build\megaatmega2560\src\control.cpp.o (symbol from plugin):(.text+0x0): first defined here
.pio\build\megaatmega2560\src\main.cpp.o (symbol from plugin): In function `Queue':
(.text+0x0): multiple definition of `mod_G_type'
.pio\build\megaatmega2560\src\control.cpp.o (symbol from plugin):(.text+0x0): first defined here
.pio\build\megaatmega2560\src\main.cpp.o (symbol from plugin): In function `Queue':
(.text+0x0): multiple definition of `mod_R_type'
.pio\build\megaatmega2560\src\control.cpp.o (symbol from plugin):(.text+0x0): first defined here
.pio\build\megaatmega2560\src\main.cpp.o (symbol from plugin): In function `Queue':
(.text+0x0): multiple definition of `mod_Y_type'
.pio\build\megaatmega2560\src\control.cpp.o (symbol from plugin):(.text+0x0): first defined here
.pio\build\megaatmega2560\src\main.cpp.o (symbol from plugin): In function `Queue':
(.text+0x0): multiple definition of `dd1_G_type'
.pio\build\megaatmega2560\src\control.cpp.o (symbol from plugin):(.text+0x0): first defined here
.pio\build\megaatmega2560\src\main.cpp.o (symbol from plugin): In function `Queue':
(.text+0x0): multiple definition of `dd1_R_type'
.pio\build\megaatmega2560\src\control.cpp.o (symbol from plugin):(.text+0x0): first defined here
.pio\build\megaatmega2560\src\main.cpp.o (symbol from plugin): In function `Queue':
(.text+0x0): multiple definition of `dd1_Y_type'
.pio\build\megaatmega2560\src\control.cpp.o (symbol from plugin):(.text+0x0): first defined here
.pio\build\megaatmega2560\src\main.cpp.o (symbol from plugin): In function `Queue':
(.text+0x0): multiple definition of `fx_G_type'
.pio\build\megaatmega2560\src\control.cpp.o (symbol from plugin):(.text+0x0): first defined here
.pio\build\megaatmega2560\src\main.cpp.o (symbol from plugin): In function `Queue':
(.text+0x0): multiple definition of `fx_R_type'
.pio\build\megaatmega2560\src\control.cpp.o (symbol from plugin):(.text+0x0): first defined here
.pio\build\megaatmega2560\src\main.cpp.o (symbol from plugin): In function `Queue':
(.text+0x0): multiple definition of `fx_Y_type'
.pio\build\megaatmega2560\src\control.cpp.o (symbol from plugin):(.text+0x0): first defined here
.pio\build\megaatmega2560\src\main.cpp.o (symbol from plugin): In function `Queue':
(.text+0x0): multiple definition of `rev_G_type'
.pio\build\megaatmega2560\src\control.cpp.o (symbol from plugin):(.text+0x0): first defined here
.pio\build\megaatmega2560\src\main.cpp.o (symbol from plugin): In function `Queue':
(.text+0x0): multiple definition of `rev_R_type'
.pio\build\megaatmega2560\src\control.cpp.o (symbol from plugin):(.text+0x0): first defined here
.pio\build\megaatmega2560\src\main.cpp.o (symbol from plugin): In function `Queue':
(.text+0x0): multiple definition of `rev_Y_type'
.pio\build\megaatmega2560\src\control.cpp.o (symbol from plugin):(.text+0x0): first defined here
.pio\build\megaatmega2560\src\main.cpp.o (symbol from plugin): In function `Queue':
(.text+0x0): multiple definition of `dbug_data'
.pio\build\megaatmega2560\src\control.cpp.o (symbol from plugin):(.text+0x0): first defined here
.pio\build\megaatmega2560\src\main.cpp.o (symbol from plugin): In function `Queue':
(.text+0x0): multiple definition of `dbug_address'
.pio\build\megaatmega2560\src\control.cpp.o (symbol from plugin):(.text+0x0): first defined here
`

**Comment by bauerbyter** [comment]
Found the Problem, moved the global variables into public.

**Comment by MrHaroldA** [comment]
These are the best issues; the ones that solve themselves ;)
